### ISSUE TITLE
[iOS] 卡顿掉帧问题

### ISSUE THREAD

**Issue by Frenqy** [BanGround/BanGround-Unity#1]
设备型号：iPhone ？/ iPad ？
系统版本：iOS 114.514

## 使用 BASS引擎 正常打歌是否卡顿：
（简单，参考谱面2940）（是 / 否）
（困难，参考谱面12038） （是 / 否）

## 使用 FMOD引擎 正常打歌是否卡顿：
（简单，参考谱面2940）（是 / 否）
（困难，参考谱面12038） （是 / 否）

## 使用 BASS引擎 使用DoubleTime打歌是否卡顿：
（简单，参考谱面2940）（是 / 否）
（困难，参考谱面12038） （是 / 否）

## 使用 FMOD引擎 使用DoubleTime打歌是否卡顿：
（简单，参考谱面2940）（是 / 否）
（困难，参考谱面12038） （是 / 否）

## Auto模式使用 BASS引擎 自动打歌是否卡顿：
（简单，参考谱面2940）（是 / 否）
（困难，参考谱面12038） （是 / 否）

## Auto模式使用 FMOD引擎 自动打歌是否卡顿：
（简单，参考谱面2940）（是 / 否）
（困难，参考谱面12038） （是 / 否）

## Auto模式使用 BASS引擎 自动打歌同时模仿打歌动作点击屏幕 是否卡顿：
（简单，参考谱面2940）（是 / 否）
（困难，参考谱面12038） （是 / 否）

## Auto模式使用 FMOD引擎 自动打歌同时模仿打歌动作点击屏幕 是否卡顿：
（简单，参考谱面2940）（是 / 否）
（困难，参考谱面12038） （是 / 否）

**Comment by ggdg123** [comment]
设备型号：iPad 2018
系统版本：iOS12. 3. 1

使用 BASS引擎 正常打歌是否卡顿：
（简单，参考谱面2940）（ 否）
（困难，参考谱面12038） （是) 

使用 FMOD引擎 正常打歌是否卡顿：
（简单，参考谱面2940）（否）
（困难，参考谱面12038） （是）

使用 BASS引擎 使用DoubleTime打歌是否卡顿：
（简单，参考谱面2940）（ 否）
（困难，参考谱面12038） （是 ）

使用 FMOD引擎 使用DoubleTime打歌是否卡顿：
（简单，参考谱面2940）（是 ）
（困难，参考谱面12038） （是 ）

Auto模式使用 BASS引擎 自动打歌是否卡顿：
（简单，参考谱面2940）（否）
（困难，参考谱面12038） （ 否）

Auto模式使用 FMOD引擎 自动打歌是否卡顿：
（简单，参考谱面2940）（否）
（困难，参考谱面12038） （否）

Auto模式使用 BASS引擎 自动打歌同时模仿打歌动作点击屏幕 是否卡顿：
（简单，参考谱面2940）（否）
（困难，参考谱面12038） （是）

Auto模式使用 FMOD引擎 自动打歌同时模仿打歌动作点击屏幕 是否卡顿：
（简单，参考谱面2940）（是 ）
（困难，参考谱面12038） （是 ）

**Comment by Frenqy** [comment]
在升级Unity后问题得到了暂时的解决
