### ISSUE TITLE
关于游戏se和语音

### ISSUE THREAD

**Issue by botax-issue** [BanGround/BanGround-Unity#12]
## Description / 问题描述
希望将游戏打歌影响手感类的音效和语音和按钮等音效音量调整分开 方便需要单独关se或者语音的玩家
## How to Reproduce / 如何复现
無
## Device Info / 设备信息
Redmi K20 Pro MIUI11 20.3.27 Android 10
***
Sender Platform: QQ
Sender ID: 773606041

**Comment by GEEKiDoS** [comment]
done in eedd797e1d
