### ISSUE TITLE
打歌时出现的奇怪延迟问题

### ISSUE THREAD

**Issue by Frenqy** [BanGround/BanGround-Unity#14]
#### 问题描述一：
![image](https://user-images.githubusercontent.com/28777951/78687466-c50e7a80-7926-11ea-92ae-5a5dab1b1284.png)

#### 问题描述二：
![image](https://user-images.githubusercontent.com/28777951/78687511-d0fa3c80-7926-11ea-9304-692e21d38407.png)

#### 问题描述三：
轮子哥曰：暂停后resume有几率复现

**Comment by Zhouzerong233** [comment]
resume的bug多了去了，比如auto酱resume会出现奇怪的miss

**Comment by KCFindstr** [comment]
`878beedaf7`: Try to sync audio timeline aggressively. Wait for the next release to see if problem resolved.
Some phenomena sound like an offset issue. Visual offset adjustment is in progress.

**Comment by Frenqy** [comment]
已找到稳定复现方法：
1. 使打歌时帧率低于60，在卡顿状态运行一段时间（此时sync值仍然在0左右浮动）
2. 恢复帧率，可见sync值瞬间变大，由于同步机制，谱面速度会发生改变以逐渐适应音频，造成不同步

**Comment by KCFindstr** [comment]
确认是音频引擎在卡顿时更新不及时导致获取的音频时间错误。解决方案：开音频线程

**Comment by AECBanana** [comment]
?

**Comment by AECBanana** [comment]
等个cri

**Comment by Frenqy** [comment]
问题仅出现在fmod上，考虑到bass存在的暂停fail/性能占用高问题，建议两个引擎一起改为手动update

或者等一个cri
