### ISSUE TITLE
小脑洞：关于判定具体消息

### ISSUE THREAD

**Issue by zeronsama** [BanGround/BanGround-Unity#15]
添加一个mod，游戏中不显示判定等级，全部改成显示±x ms，最后再加入回放或静态谱面图，供玩家观看各个note的偏移

**Comment by Frenqy** [comment]
显示±x ms已经纳入考虑
回放或静态图暂时不予考虑，建议开源后自行制作或等待n.0版本后开发

**Comment by LingFeng-bbben** [comment]
建议自个儿录手元
但是不能录屏是为啥呢

**Comment by LingFeng-bbben** [comment]
已经加入豪华套餐
