### ISSUE TITLE
偏移描述

### ISSUE THREAD

**Issue by botax-issue** [BanGround/BanGround-Unity#17]
## Description / 问题描述
将偏移的描述改为“early多则调大，late多则调小”之类的更一目了然 的描述
## How to Reproduce / 如何复现
不用复现（）
## Device Info / 设备信息
ipad2018
***
Sender Platform: QQ
Sender ID: 1405116404

**Comment by AECBanana** [comment]
下次一定

**Comment by zeronsama** [comment]
[Q&A写了](https://wiki.banground.fun/#/qa?id=%e5%bb%b6%e8%bf%9f%e8%b0%83%e8%8a%82)

**Comment by LingFeng-bbben** [comment]
改了
