### ISSUE TITLE
Auto酱在resume后打击的前几个note有概率miss

### ISSUE THREAD

**Issue by Frenqy** [BanGround/BanGround-Unity#20]
RT测试谱面：任意
复现方法：（极低概率）在note到达判定线被auto酱击打的一瞬间点击暂停，有可能无法被判定。可见auto酱点击轨道的粒子效果，但是note并没有被判定，在resume时跟着回滚。当note再次到达判定线时，auto酱不会再次尝试击打该note，造成miss

**Comment by Frenqy** [comment]
美工描述：
![IMG_20200409_190622](https://user-images.githubusercontent.com/28777951/78888965-526fdd00-7a95-11ea-84c5-6131cc2866a9.jpg)
![image](https://user-images.githubusercontent.com/28777951/78888982-5996eb00-7a95-11ea-8a7b-cdc9b67c7f5e.png)

**Comment by KCFindstr** [comment]
Fixed in `be43f8bd32`. Need verification.

**Comment by KCFindstr** [comment]
No longer receive such report.
