### ISSUE TITLE
关于FC/AP记录无法覆盖Clear记录或是被Clear记录覆盖的问题

### ISSUE THREAD

**Issue by 6QHTSK** [BanGround/BanGround-Unity#21]
如题，来自一个用六兆年来调延迟无意间FC却因为分低覆盖不了之前的clear记录的手残……
之前好像好几次提过这个问题（从0.1.8提到0.5.0），在群里估计都忘了，这次提在issue。
目前的类似情况包括，FC/AP却覆盖不了之前前面全p断在后面clear记录（或是无聊dt打的记录），断在后面前面全p的成绩（或者是dt打完忘记exit）因为分高覆盖了FC/AP记录。（这都很让人痛苦，选歌列表FC/AP歌曲-1）
目前以分数为核心的成绩更新体系会导致未来执行鱼干系统的时候，该问题可能会影响到系统或者玩家对于FC/AP时获取鱼干的理解和计算。所以宜将CL/FC/AP体系和分数体系分开，分别运行。
由于mod辅助的原因，建议在未来除了倍速的成绩，一旦达成FC/AP，即可覆盖之前的clear/FC记录（即不记录dt/ht mod成绩）；或者是把dt/ht/正常速的成绩显示分开，开dt mod显示dt成绩，开ht mod显示ht成绩等（即分开 dt/ht/正常 的成绩）。
还有，为什么我排版之后issue变成了md格式

**Comment by AECBanana** [comment]
但是排行榜就是根据分数来排的。。。

**Comment by Frenqy** [comment]
CL/FC/AP体系 **将会** 和分数体系分开计算与覆盖。但是mod成绩的处理还未决定。（issue本来就是md啊）

**Comment by Frenqy** [comment]
0fde16c4提交已实现：结算时分数与评级分开计算
现存问题：倍速模组分数尚未与普通模式分数区分存放与计算

**Comment by LingFeng-bbben** [comment]
把打出来的分数使用的mod也存一下吧

**Comment by LingFeng-bbben** [comment]
注意现在仍有bug
在结算界面会直接显示上一次更好的成绩和clear mark

**Comment by Frenqy** [comment]
下午盲修过了
