### ISSUE TITLE
FS存储的删除逻辑/视频缓存删除

### ISSUE THREAD

**Issue by LingFeng-bbben** [BanGround/BanGround-Unity#26]
复现步骤
kirapack内仅有一首歌
1.导入kirapack（旧）
2.游戏内删除对应歌曲
3.导入kirapack（新）
4.进入游戏，为旧kirapack内数据
查沙盒内旧kirapack未被删除，
且temp内视频未删除（filmlive 在kirapack内和temp内占用了**双倍空间**）
@GEEKiDoS 修修

**Comment by GEEKiDoS** [comment]
听说很久之前就修好了 但是没人试

**Comment by Frenqy** [comment]
@GEEKiDoS iOS重新打包后丢失谱面数据的bug依旧没好

**Comment by Frenqy** [comment]
iOS重新打包后丢失谱面数据的bug已修复
删除功能部分损坏

**Comment by Frenqy** [comment]
不知道好没好

**Comment by AECBanana** [comment]
bzd
2020年5月3日 15:03，Frenqy <notifications@github.com<mailto:notifications@github.com>> 写道：



不知道好没好
