### ISSUE TITLE
退出游戏的问题

### ISSUE THREAD

**Issue by botax-issue** [BanGround/BanGround-Unity#27]
## Description / 问题描述
在退出游戏时（原本是点两下返回键），如果多次点击返回键，会出现不断退出的假象
## How to Reproduce / 如何复现
选歌页面多次点击返回键
## Device Info / 设备信息
meizu m3
***
Sender Platform: QQ
Sender ID: 475817716

**Comment by Frenqy** [comment]
fixed in 23da962
