### ISSUE TITLE
Live结束后还可以操作打歌界面/谱面长度超出音频长度时发生的特性

### ISSUE THREAD

**Issue by 6QHTSK** [BanGround/BanGround-Unity#28]
小特性，当出现Clear/FC/AP的那个遮罩时，还可以点击原有轨道位置操作打歌界面，发出敲击声。
另外，当谱面长度超出音频长度时，会出现于音频结束时提前关门的现象，有时直接导致auto酱全Perfect但Fail的特性。（也就是永远无法AP）
当然上面这个问题的**最优解决方案**还是解决掉**写出这个谱面的谱师**。
~~但可不可以关门时间取决于音频和谱面的最长时间呢？~~
~~或者可以用这两个特性整点小活？~~
另外，auto酱在关门后4s还在打歌，够敬业！

**Comment by LingFeng-bbben** [comment]
关门后还能敲是用来鼓掌的（确信
第二个问题完全就是谱师的错吧，，，

**Comment by Frenqy** [comment]
特性1将会修复
特性2将会修理谱师

顺带一问是什么情况下会fail？
fail时音频长度那段的note数小于总数的60%了吗？
因为是根据总acc计算的评级结果，理论上除这种情况外不会fail

**Comment by 6QHTSK** [comment]
fail的情况就是音频长度+4s左右小于总数的60%，就是这种情况会fail。

**Comment by Frenqy** [comment]
fixed in  2b17faac91
