### ISSUE TITLE
绿条尾端被盖住了

### ISSUE THREAD

**Issue by AECBanana** [BanGround/BanGround-Unity#29]
本家是尾端盖住，现在是尾端被盖住

**Comment by AECBanana** [comment]
![IMG_E71D2E70688F-1](https://user-images.githubusercontent.com/60141130/80281099-6b39ed00-873b-11ea-85e1-e191221cb028.jpeg)
贴个图

**Comment by Frenqy** [comment]
fixed in eb79df2efb
