### ISSUE TITLE
Acc在结算时的显示与选歌列表的显示不一致

### ISSUE THREAD

**Issue by 6QHTSK** [BanGround/BanGround-Unity#3]
结算时候的Acc（99.89%）与选歌列表更新的Acc（99.90%）不同。实际acc为99.8970%（6gr/1165note），出现概率低，其可能会影响对临界Acc的评级判断。

设备：安卓 荣耀V8
BanGround版本号： 0.4.3

**Comment by KCFindstr** [comment]
Fixed in b70bcbb2c9. Will take effect in 0.4.4.
