### ISSUE TITLE
0.6.1 Windows版出现的一堆问题

### ISSUE THREAD

**Issue by 6QHTSK** [BanGround/BanGround-Unity#31]
问题1：不能正确的播放BGA（有图片的谱面背景一直是黑色的）
问题2：不能正确的读取脚本
问题3：发完crashes包之后无法播放声音，只能播放音效（包括提示音，key音（在设置中））
问题4：发完crashes包之后无法播放谱面，且S值始终无法出现
问题5（此问题多次表现不一样，但是最终以出现Game Over然后崩溃结局）：
1.暂停-resume-Game Over；（仅出现一次）
2.暂停-resume-暂停-Retry-GameOver
3.暂停-resume-暂停-exit-GameOver；（仅出现一次，且之后的情况是exit和resume按键均不可按）期间在dev窗口有输出信息（已发在群里）
问题6 ： 暂停-Retry-正常重试歌曲-无法用鼠标操控界面的任何元素，弹出的暂停界面无鼠标显示（就是那几个像素点都找不到了）
问题7：关于GameOver窗口，只要出现必然崩溃。另外，若在歌曲开头（audioTime<0）时触发，则会重复发出”Are You Ready“提示音
目前的问题发现的就是这么多，将持续寻找问题

**Comment by 6QHTSK** [comment]
补充，默认音频引擎又变回了bass而不是fmod

**Comment by Frenqy** [comment]
问题1：已修复
问题2：大概已修复
问题3：已修复
问题4：已修复
问题5：仍在排查
问题6：双鼠标暂时bug较多，缓慢修复中
问题7：草
问题8：无法复现 全新加载时音频引擎为fmod

**Comment by Frenqy** [comment]
大概修完了？
