### ISSUE TITLE
0.6.2版本轮子问题

### ISSUE THREAD

**Issue by ButtercatT** [BanGround/BanGround-Unity#32]
运行环境:android10 骁龙865

1.选歌轮子划到列表头会自动弹到列表尾部。

2. 调整轨道长度时拖动条会自动消失导致卡死在长度调整界面，只能强制退出游戏解决

**Comment by AECBanana** [comment]
下次一定

iPhoneから送信

2020/04/29 午前11:12、ButtercatT <notifications@github.com>のメール:

﻿

运行环境:android10 骁龙865

1.选歌轮子划到列表头会自动弹到列表尾部。

  1.  调整轨道长度时拖动条会自动消失导致卡死在长度调整界面，只能强制退出游戏解决

**Comment by Frenqy** [comment]
问题2已修复

**Comment by Frenqy** [comment]
轮子换掉了
