### ISSUE TITLE
关于退出时背景显示异常的问题

### ISSUE THREAD

**Issue by ReiKohaku** [BanGround/BanGround-Unity#33]
在选歌界面退出游戏时，歌曲的背景图片会突然缩小，之后才弹出GAME OVER（顺便吐槽GAME OVER什么意思啊，写SEE YOU NEXT TIME不好吗）界面。
看起来很违和，希望修复。

**Comment by KCFindstr** [comment]
?所以为啥要支持选歌界面退出游戏 不想上架ios了？

**Comment by Frenqy** [comment]
没问题

**Comment by AECBanana** [comment]
毛闷台 改成西又奈斯太慕了
