### ISSUE TITLE
偶现打歌结束后无法结算的问题

### ISSUE THREAD

**Issue by Frenqy** [BanGround/BanGround-Unity#36]
rt,zsbd
表现为时间显示（S）值左侧在结束后回到歌曲开始时的值，右侧的值则回退后继续增长
复现方法未知，bug视频见2020.05.21日内测群视频

**Comment by AECBanana** [comment]
我不懂 我不知道 
![$)SKKU3@(ZF58~~LAYP5D7U](https://user-images.githubusercontent.com/60141130/82629504-80167d00-9c22-11ea-9c84-2809ca5c32ee.jpg)

**Comment by KCFindstr** [comment]
我不懂 我不知道

**Comment by Frenqy** [comment]
str椰叶修好了
