### ISSUE TITLE
部分用户开启app会有长时间黑屏

### ISSUE THREAD

**Issue by Frenqy** [BanGround/BanGround-Unity#37]
原因为开启app时在尝试连接unity？暂时不知道具体原因

**Comment by ReiKohaku** [comment]
解决方案一：把有奶提的网站都代理掉
解决方案二：打包以后改源码
解决方案三：鲨了有奶提，还有虚幻五（？？？

**Comment by Frenqy** [comment]
Konsole的问题 已修复
