### ISSUE TITLE
0.7.2 版本表现的一些bug或特性

### ISSUE THREAD

**Issue by 6QHTSK** [BanGround/BanGround-Unity#38]
1. 制谱器bug，图片已经发在群里了（29日0点左右），主要表现在metadata 和 timing 标签 cancel掉后出现在轨道后方，且轨道的小节号被背景掩盖
2. 谱面打完结束之后（AP,FC,CL）的提示之后会短暂的回到原打歌界面，然后再结算（0.7.1历史遗留问题）
3. 删除谱面的时候，红色遮罩不适配现在的UI（上面有圆角，下面是直角，且下面不够长）
4. retry 翻译仅在结算界面有翻译，但是在暂停界面没有翻译，back在任何地方都没有翻译
5. New谱面也有类似制谱器的问题：setting和mod songname这几个跑到上面来了，图片已经发在群里了（29日0点左右）
6. 制谱器部分的建议，建议开发删除某个谱面难度的选项，手滑建错难度无法删除
想到了，发现了再加

**Comment by Frenqy** [comment]
1、Windows平台DX独有问题
2、已修复
3、暂时移除了删除功能
4、排查中
5、同1
6、同3

**Comment by Frenqy** [comment]
1、已修复
2、已修复
3、暂时移除了删除功能，后续会和红心/文件夹存放功能一起上线
4、已修复
5、已修复
6、同3
