### ISSUE TITLE
语音结束前点击无法start

### ISSUE THREAD

**Issue by zeronsama** [BanGround/BanGround-Unity#4]
在选歌界面如果选歌提示音未结束之前点击start，会有开始live的提示音，但是仍停留在选歌界面上，然后不管选歌提示音结束与否点击start都无法进入live，拖动选歌轮到其他歌点击start可以正常live

**Comment by Frenqy** [comment]
de8f67e3已修复，现在在场景加载完成之前不允许点击Start
