### ISSUE TITLE
[TODO] 0.7.4版本卫星

### ISSUE THREAD

**Issue by Frenqy** [BanGround/BanGround-Unity#40]
- [x] ~UnityAudioProvider~ Unity已经没救了 放弃吧

- [x] 选歌轮子回滚

- [ ] 选歌轮子优化

- [ ] 文件夹、折叠、收藏、删除功能

- [ ] ~URP回滚到内置渲染管线~ 雨我无瓜

- [x] 选歌界面背景刷新

**Comment by KCFindstr** [comment]
- [x] Beat snap支持1/8
- [ ] 鲨了老版本谱面格式
- [ ] 制谱器支持fuwafuwa note
- [ ] 制谱器热键
- [ ] 制谱器墓碑机制

**Comment by Frenqy** [comment]
0.8.0了
