### ISSUE TITLE
0.7.3 IOS问题反馈

### ISSUE THREAD

**Issue by Kevin-genius-x** [BanGround/BanGround-Unity#41]
1.小概率情况下，歌曲开始前摇会消失，进入的瞬间开始打歌，导致MISS
2.强烈建议做回删除功能
3.含有视频的谱面视频无法播放

设备型号：iPad 7.5 （2018,128G，未越狱，IOS13.6）

**Comment by Kevin-genius-x** [comment]
4.附加：小概率情况下，Note会瞬移掉落

**Comment by Frenqy** [comment]
问题1和4：需要更多复现步骤信息
问题2：下个版本会修复
问题3：无法复现 请提供出现问题的kirapack

**Comment by Frenqy** [comment]
0.8.0了
