### ISSUE TITLE
0.7.3 Offset Guide引用谱面错误等几个问题

### ISSUE THREAD

**Issue by 6QHTSK** [BanGround/BanGround-Unity#43]
1. 严重bug，offset guide 谱面来自于进入offset guide前选歌界面停留的那个谱面，而非之前的offset guide谱面。
2. 建议：settings 的拖动滑动的横向距离扩大，不习惯在有字的地方滑动，更喜欢在稍右边无字的地方滑动。
3. 吐槽：mod的那条鱼和整个界面违和感也太大了吧。虽然有特殊意味但是还是很想吐槽。
4. 期望：能不能保留0.6.2的皮肤（本人非常喜欢，所有我的视频封面都是拿0.6.2截的）甚至远古版本的皮肤供切换。
5. 期望：之前的点击空白处显示整张封面的特性能不能加回来。
6. 期望：note染色功能，这样就可以在banground中还原技能键了(x
7. 想到了再加……

**Comment by Frenqy** [comment]
1.已修复
2.已修复
3. @美工
4.由于人手不足且开发组目前都比较忙，皮肤功能开发优先级较低，只能给个会做的卫星
5.这个功能之前由于优化问题移除了，如果加回来只能加个阉割版的，会考虑（显示整张封面时背景是模糊的，模糊这个功能对移动端GPU负担很大，会造成发热掉帧）
6.这个功能已经做好了，暂时没开放

**Comment by Frenqy** [comment]
0.8.0了
