### ISSUE TITLE
0.8.0 版本的判定线比实际节奏的时间点要早

### ISSUE THREAD

**Issue by shiawasenahikari** [BanGround/BanGround-Unity#44]
我使用 Offset Guide 将判定偏移调成了 +100，然后在实际打歌界面打 Tutorial 时，发现 note 下落得还是比节奏点快了一点。然后当 note 落到判定线上时我击打会出现 early 的 great 评价，如果我将手稍微放到判定线下方一点，完全跟着鼓点打的话，就会出现 perfect 评价。

设备是 iPad 6，系统是 iOS 13.5.1。

**Comment by Frenqy** [comment]
美工已在群内解答
