### ISSUE TITLE
音符样式为第3时黑键难以辨别

### ISSUE THREAD

**Issue by xiaobu1071** [BanGround/BanGround-Unity#45]
使用第3种note样式并开启节奏视觉辅助会使得变黑的按键辨别率降低，可能要优化一下对比度

**Comment by KCFindstr** [comment]
所有note染色是统一的，只能看美工能否修正一下染色图。
你可以通过制谱器的speed view修正谱面的染色效果来临时解决。

**Comment by AECBanana** [comment]
这就去修

**Comment by AECBanana** [comment]
修了
