### ISSUE TITLE
ver.0.8 安卓选歌界面GPU资源占用过高

### ISSUE THREAD

**Issue by ButtercatT** [BanGround/BanGround-Unity#46]
设备:三星s20，android 10
![Screenshot_20200805-124950_BanGround](https://user-images.githubusercontent.com/44700688/89398817-2e22c500-d744-11ea-9b14-5ab792481049.jpg)
见图右上角，GPU在选歌界面占用率接近70%，打歌时为25%左右。
停留在选歌界面一段时间后，手机温度快速升高，游戏帧数由120帧强制降低到60帧，GPU占用率降低为30%左右。

**Comment by Frenqy** [comment]
请按照以下步骤进行问题排查：
1、清空app数据（清空曲库）
2、打开app，查看GPU与CPU占用率

**Comment by ButtercatT** [comment]
![Screenshot_20200805-184220_BanGround](https://user-images.githubusercontent.com/44700688/89403869-9a54f700-d74b-11ea-8628-01f6cca55172.jpg)
全部数据清空之后，占用率平均在40左右

**Comment by StarWishNya** [comment]
在导入核弹包后gpu和cpu占用明显提高并且加载速度大幅度延长

**Comment by ButtercatT** [comment]
初始占用40%感觉还是太高了，歌曲数量对gpu负担带来的影响也比较明显，等一个椰椰们的优化
ヾ(❀╹◡╹)ﾉ~

**Comment by Frenqy** [comment]
收到，正在排查，理论上GPU占用不会高于20

**Comment by KCFindstr** [comment]
内存泄漏问题已修复 GPU占用原因暂时未知

**Comment by KCFindstr** [comment]
请查看0.9.0版本是否有修复

**Comment by ButtercatT** [comment]
目前暂时没有出现掉帧问题了（ipad pro的掉帧也修复了），应该就是内存泄漏的问题，后续会继续观察
