### ISSUE TITLE
下个版本记得把退出选项写上

### ISSUE THREAD

**Issue by zeronsama** [BanGround/BanGround-Unity#5]
# 下个版本记得把退出选项写上
###### 下个版本记得把退出选项写上
*下个版本记得把退出选项写上*
**下个版本记得把退出选项写上**
***下个版本记得把退出选项写上***

**Comment by qingfua** [comment]
？？？？
不记得 爬

**Comment by zeronsama** [comment]
# Remember to write the exit option in the next version
# N'oubliez pas d'écrire l'option de sortie dans la prochaine version
# 次のバージョンで終了オプションを必ず記述してください
# 다음 버전에서 종료 옵션을 작성하십시오
# อย่าลืมเขียนตัวเลือกออกในรุ่นถัดไป

¿反应这么快？

**Comment by LingFeng-bbben** [comment]
markdown带师

**Comment by Frenqy** [comment]
需要退出选项的是win版还是安卓版？

**Comment by zeronsama** [comment]
都要

**Comment by Frenqy** [comment]
803abf1e 已实现 2s内两次点击返回/ESC即可退出app
