### ISSUE TITLE
关于引导曲的两个BUG

### ISSUE THREAD

**Issue by xiaofeng19** [BanGround/BanGround-Unity#51]
设备一：iPad（第6代） 系统：iPadOS 13.6
设备二：Redmi K20 Pro 系统：MIUI 12.0.2稳定版 安卓版本：10

BUG1. 点选设置里面的offset guide后，会先弹出unsupported提示，此时点X的话选歌界面所有歌选择时都会变成那首引导曲

BUG2. 在引导曲在说ready和音乐开始前这段时间内点右上角退出的话（早了和晚了都是正常的），虽然界面会正常退出，但引导曲的音乐会继续播放

**Comment by GEEKiDoS** [comment]
@LingFeng-bbben 轮子哥修修谱面

**Comment by Frenqy** [comment]
@KCFindstr 点X后“offset guide"标识符没重置
