### ISSUE TITLE
[Bug][Android]无法导入Kirapack

### ISSUE THREAD

**Issue by Frenqy** [BanGround/BanGround-Unity#53]
rt，无法稳定复现

可能复现步骤：
从外部打开kirapack选择使用bg打开，此时无论客户端是开启还是关闭，都无法导入
经过排查，kirapack并没有正常复制到Inbox目录
无log

**Comment by AECBanana** [comment]
没人修 摸了

发自我的iPhone

在 2020年8月15日，下午11:33，Frenqy <notifications@github.com> 写道：

﻿

rt，无法稳定复现

可能复现步骤：
从外部打开kirapack选择使用bg打开，此时无论客户端是开启还是关闭，都无法导入
经过排查，kirapack并没有正常复制到Inbox目录
无log
