### ISSUE TITLE
内存溢出操作

### ISSUE THREAD

**Issue by AECBanana** [BanGround/BanGround-Unity#56]
选歌列表 一直点排序按钮 你的游戏占用内存就会biubiu往上涨
![CD54399E4AD4DF6A47D0014387014C0A](https://user-images.githubusercontent.com/60141130/91313643-2f498e00-e7e8-11ea-9d58-1f7a1024cd90.png)

**Comment by KCFindstr** [comment]
Fixed in 306c5a
