### ISSUE TITLE
0.8.0 版本判定调节向导里 note 过了判定线后会突然加速

### ISSUE THREAD

**Issue by shiawasenahikari** [BanGround/BanGround-Unity#57]
issue 里贴不了录屏，发在群里了，各位椰叶应该已经看到了。主要问题就是不论透视校正开启与否，在判定调节向导里，note 过了判定线都会突然加速，在单机打歌状态下就没有这个问题，单机打歌时透视校正开启时，note 过了判定线仍然正常下落；透视校正关闭时，note 过了判定线会突然加速。

用一张表总结一下：
　――――――　――――――――――――――――　――――――――――――――――
｜　　　　　　｜　　　　　透视校正：开　　　　　｜　　　　　透视校正：关　　　　　｜
　――――――　――――――――――――――――　――――――――――――――――
｜单机打歌模式｜ＮＯＴＥ过判定线后正常下落　　　｜ＮＯＴＥ过判定线后突然加速　　　｜
　――――――　――――――――――――――――　――――――――――――――――
｜判定调节向导｜ＮＯＴＥ过判定线后突然加速（＊）｜ＮＯＴＥ过判定线后突然加速　　　｜
　――――――　――――――――――――――――　――――――――――――――――

另外就是双押线方面也有这样的问题，单机打歌模式一切正常，而判定调节向导里，不论双押线是否开启，都不显示双押线。

设备：iPad 6，系统：iOS 13.5.1。

**Comment by Frenqy** [comment]
将会在下个版本修复
提供临时解决方案：正常进入一次打歌之后退出，此时进入判定调节向导可以恢复

**Comment by KCFindstr** [comment]
已修复 请等待下个版本发布
