### ISSUE TITLE
难度内建无法复制bpm数值

### ISSUE THREAD

**Issue by AECBanana** [BanGround/BanGround-Unity#61]
![0T5 SF%1J12@HIK7P`4L%PW](https://user-images.githubusercontent.com/60141130/99325288-fa157f00-28b0-11eb-9487-027106aaccd6.png)
![6)PP2UR{{@Z5Z~B37)~38C3](https://user-images.githubusercontent.com/60141130/99325374-2e893b00-28b1-11eb-96d7-67066371045a.png)
![KM@L64GD1R9HK`@M4SJEJ2M](https://user-images.githubusercontent.com/60141130/99325394-3c3ec080-28b1-11eb-8344-e561d2f14877.png)

**Comment by GEEKiDoS** [comment]
Ctrl+C, Ctrl+V
移动端爬

**Comment by AECBanana** [comment]
？

**Comment by GEEKiDoS** [comment]
Ctrl+C, Ctrl+V 可以用，安卓可以长按复制，无法复现无法复制的情况
