### ISSUE TITLE
游戏重启后还是bass 切换fmod还是显示bass，但切换后确实是显示bass实际fmod

### ISSUE THREAD

**Issue by AECBanana** [BanGround/BanGround-Unity#63]
![R54E73WWEU_1JDG(0 QYE4P](https://user-images.githubusercontent.com/60141130/99326763-7ad57a80-28b3-11eb-9980-690be7a5b17f.png)

**Comment by AECBanana** [comment]
还是有啊 椰叶在干啥呢

**Comment by KCFindstr** [comment]
Fixed in 53533f8.
