### ISSUE TITLE
title的username显示不了了

### ISSUE THREAD

**Issue by AECBanana** [BanGround/BanGround-Unity#66]
![QQ图片20201117135736](https://user-images.githubusercontent.com/60141130/99352061-e97afe00-28dc-11eb-8e56-7ef6d2fe9e86.png)

**Comment by GEEKiDoS** [comment]
这不是因为你把那个prefab删了吗 自己修

**Comment by AECBanana** [comment]
不会修

**Comment by Frenqy** [comment]
不会修你就revert回去 把预制体还回来------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;AECBanana&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年11月17日(星期二) 下午2:14
收件人:&nbsp;&quot;BanGround/BanGround-Unity&quot;<BanGround-Unity@noreply.github.com&gt;;
抄送:&nbsp;&quot;Frenqy&quot;<411937015@qq.com&gt;;&quot;Assign&quot;<assign@noreply.github.com&gt;;
主题:&nbsp;Re: [BanGround/BanGround-Unity] title的username显示不了了 (#66)

**Comment by AECBanana** [comment]
修了
