### ISSUE TITLE
0.9.0关于制谱器绿条删除操作的bug

### ISSUE THREAD

**Issue by 6QHTSK** [BanGround/BanGround-Unity#67]
在选中绿条的情况下选择delete，绿条消失，但是，改变时间条（包括下方时间轴和拖动左方预览条），该绿条突然出现（选中状态），此时对该绿条头尾进行删除操作。报错内容NullReferenceException: Object reference not set to an instance of an object。此时保存，重新进入后，该绿条消失。
其它问题等能复现再上报

**Comment by KCFindstr** [comment]
Fixed in Kirakira-Games/BanGround-Unity@ead534d218ce2576068c8f7ba2256d09c2646136
