### ISSUE TITLE
# 催更Windows的0.5.0版本更新

### ISSUE THREAD

**Issue by zeronsama** [BanGround/BanGround-Unity#7]
### Sila muat naik pakej dengan cepat untuk Windows 0.5.0

***

|请|快速|
| :----------: | :----------: |
|上传|Windows|
|0.5.0的|安装包|

- [x] **Android 0.5.0**
- [x] **iOS 0.5.0**
- [x] **Windows 0.5.0**
- [x] *Windows 零。四。一*

**Comment by LingFeng-bbben** [comment]
等等geek修复下阴影

**Comment by Frenqy** [comment]
阴影未知原因 试试把阴影相机的clear打开一下

**Comment by LingFeng-bbben** [comment]
下包了
