### ISSUE TITLE
我摸了

### ISSUE THREAD

**Issue by KCFindstr** [BanGround/BanGround-Unity#71]
1. 编辑器窗口直接进入游戏界面（修改sceneloader，同时加载两个场景，并deactivate前一个场景的object）
2. 轻飘飘音符读谱辅助

**Comment by ReiKohaku** [comment]
椰叶你可以的
- [ ] 给编辑器添加单个、批量note的移动功能
- [ ] 给编辑器添加单个、批量note的复制/粘贴/镜像功能

**Comment by KCFindstr** [comment]
该issue已移动至kirakira games的私有库
