### ISSUE TITLE
建议将多押的同时点击线的绘制规范化

### ISSUE THREAD

**Issue by ghost** [BanGround/BanGround-Unity#77]
多押的同时点击线的绘制非常没有规律，甚至同样的按键绘制顺序会产生不同的绘制方式
我想到三种解决方案：
1、按照谱面元素的绘制顺序，绘制同时多押的点击线（还要考虑到在不同group之间的绘制顺序）
2、自动按照最短路径填充多押的点击线
3、允许谱师手动绘制多押的点击线

可能还会有更好的方案，我是想不到了……
但现在的多押的点击线的绘制确实非常没有规律

**Comment by KCFindstr** [comment]
目前多押按x坐标从左到右连接
