### ISSUE TITLE
bug：社区无法打开

### ISSUE THREAD

**Issue by Ayanami0312** [BanGround/BanGround-Unity#78]
![9258FD05-7156-4A65-8C41-778B0686106A](https://user-images.githubusercontent.com/40337241/103473147-31dc7580-4dd0-11eb-8d4a-42cac4a489ec.png)
![6971DEC7-6FED-420C-9110-E016D804AA6B](https://user-images.githubusercontent.com/40337241/103473149-356ffc80-4dd0-11eb-952c-e8fe356f5c32.png)
手机：Iphone 6 系统：12.4
社区无法正常启用

**Comment by Ayanami0312** [comment]
手机好像不能发图...我这看不到效果
报错：FormatException：String was not recognized as a vaild DateTime.
异常：社区一直处在加载状态 无法正常使用

**Comment by KCFindstr** [comment]
已收到，之后会查看原因。
注意：你的截图包含了账号相关的敏感安全信息，建议立即修改密码。

**Comment by KCFindstr** [comment]
请确认更新到BanGround最新版本以后是否还有该错误？

**Comment by Ayanami0312** [comment]
谢谢提醒
更新到0.9.1（8）后情况没有改变...

**Comment by GEEKiDoS** [comment]
请问系统语言是什么

**Comment by Ayanami0312** [comment]
zh-cn

**Comment by GEEKiDoS** [comment]
看内测群

**Comment by KCFindstr** [comment]
关闭issue，若还有问题请开新issue
