### ISSUE TITLE
成绩更新问题

### ISSUE THREAD

**Issue by ButtercatT** [BanGround/BanGround-Unity#79]
![5ad1e3e5ec21a390](https://user-images.githubusercontent.com/44700688/103534473-e3130680-4ec9-11eb-92ff-b406dac86830.jpg)
![4dd87502b56d6d48](https://user-images.githubusercontent.com/44700688/103534478-e4dcca00-4ec9-11eb-8768-dceafe532c05.jpg)
最高分成绩没有正常覆盖先前的成绩

**Comment by Frenqy** [comment]
【管理员】Findstr 14:23:10
让他提供一下Scores.bin

【管理员】Findstr 14:23:16
看看到底存进去没有
