### ISSUE TITLE
bug：简体中文下编辑器显示重字

### ISSUE THREAD

**Issue by none-id** [BanGround/BanGround-Unity#81]
![PNG图像](https://user-images.githubusercontent.com/45704666/108595370-6cb75e80-73ba-11eb-8ea6-f740f6e5629e.png)
时间点栏的左下角位置，如图。

**Comment by GEEKiDoS** [comment]
Moved to https://github.com/Kirakira-Games/BanGround-Unity/issues/73 (private)
