### ISSUE TITLE
带lua脚本的谱面导出或上传后丢失lua脚本效果

### ISSUE THREAD

**Issue by none-id** [BanGround/BanGround-Unity#82]
测试设备：输出端ipad pro 2020 ipad os 14.2   导入端：红米k30 miui 12
第一手未经转换的包，通过导入游戏转换后，自己添加object(8)设置在轨道上方显示。然后，通过内置分享功能打包，再发给安卓全面屏设备后丢失了lua脚本的特效。

**Comment by none-id** [comment]
追加一条，通过内置编辑器上传至社区后，在win10端下载（估计别的端也一样）后丢失lua脚本特效

**Comment by Frenqy** [comment]
留一下QQ号 方便在内测群找人

**Comment by KCFindstr** [comment]
关闭issue，若还有问题请开新issue
